"""V8.3-W2 — CONFIG REGISTRY: NƠI KHAI BÁO DUY NHẤT cho mọi key cấu hình.

QUY TẮC (bắt buộc từ V8.3): thêm key mới = thêm ĐÚNG 1 DÒNG vào REGISTRY.
Settings field + web Credential Center + `.env.example` + hot-reload whitelist TỰ SINH từ đây.
CẤM: hardcode key trong module, thêm field tay vào config/settings.py.

Sinh lại các mặt sau khi đổi registry:
    python -m scripts.gen_settings_stub      # config/settings.pyi (IDE type-hint)
    python -m scripts.sync_env_example       # .env.example
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Key:
    name: str  # tên field settings (snake_case) — biến env = name.upper()
    type: type  # str | int | float | bool
    default: object
    group: str  # id nhóm trong GROUP_META
    label: str = ""  # nhãn hiện trên web (chỉ dùng khi web=True)
    kind: str = "text"  # secret | text | url | number
    required: bool = False
    hot: bool = False  # True → đổi runtime qua automation.json, không cần restart
    web: bool = False  # True → hiện trong Credential Center
    env_only: bool = False  # True → KHÔNG phải Settings field (vd ANDROID_* cho build script)
    placeholder: str = ""
    note: str = ""  # comment sinh vào .env.example


def hot_keys() -> set[str]:
    """W2.3c: whitelist hot-reload automation.json — sinh từ registry."""
    return {k.name for k in REGISTRY if k.hot}


def check_env_keys(env_path: str = ".env") -> list[str]:
    """W2.3d: key trong .env không có trong registry → cảnh báo "key rác" (fail-open).

    Trả list message để caller log WARNING; không raise, không chặn boot.
    """
    try:
        from dotenv import dotenv_values

        env_keys = {key for key in dotenv_values(env_path) if key and key.strip()}
    except Exception:  # noqa: BLE001 — đọc .env lỗi thì bỏ qua check
        return []
    known = {key.name.upper() for key in REGISTRY}
    return [
        f"key rác/lạc trong .env (không có trong registry): {key}"
        for key in sorted(env_keys - known)
    ]


# (title, description) — thứ tự dict = thứ tự nhóm trên web + section .env.example.
GROUP_META: dict[str, tuple[str, str]] = {
    "llm": ("Bộ não (Groq/Gemini)", "Khóa Groq/Gemini cho bộ não viết nội dung."),
    "dashboard": (
        "Đăng nhập web",
        "Cách đăng nhập bảng điều khiển. Mặc định dùng API key; muốn dùng mật khẩu thì điền ô Mật khẩu (Session secret sẽ tự tạo).",
    ),
    "telegram": ("Cảnh báo Telegram", "Bot Telegram để báo lỗi và duyệt nhanh trên điện thoại."),
    "shopee_session": (
        "Shopee (qua trình duyệt)",
        "Lấy link Shopee qua trình duyệt đã đăng nhập sẵn. Cookie nhập ở mục Shopee Setup.",
    ),
    "sources": (
        "Nguồn xu hướng",
        "Khóa nguồn xu hướng tham khảo (Meta Ads Library, YouTube Trends).",
    ),
    "dispatch": ("Kênh đăng bài", "Khóa để tự đăng video lên YouTube/Facebook (TikTok đăng tay)."),
    "revenue": ("Doanh thu Shopee", "Cách lấy số liệu doanh thu & hoa hồng từ Shopee."),
    "assets": ("Kho ảnh/video nền", "Khóa lấy ảnh/video nền có sẵn (Pexels, Pixabay)."),
    "release": (
        "Ký số app Android",
        "Chữ ký số để đóng gói app Android (chỉ khi cần xuất bản app).",
    ),
    "media_ai": (
        "Giọng đọc (Vbee / Gemini TTS / Suno)",
        "Giọng đọc tiếng Việt (Vbee/Gemini) và nhạc nền (Suno) — dịch vụ trả phí.",
    ),
    "scoring": ("Chấm điểm sản phẩm (Module 1)", "Trọng số P, tier A/B/C, percentile."),
    "video": ("V8 Video Engine (Seedance + Gemini)", "PiAPI, budget video, autopilot, analyzer."),
    "render": ("Render & compose (Module 3)", "ffmpeg, polish, nhạc nền, VRAM guard."),
    "automation": (
        "Tự động hoá (hot-reload)",
        "Đổi runtime qua automation.json — không cần restart.",
    ),
    "browser_qa": ("Browser QA harness", "Playwright QA nền — tắt mặc định."),
    "leads": ("Lead inbox (Module 6)", "Comment/DM — tắt mặc định."),
    "ops": ("Vận hành & đa tiến trình", "Log, supervisor, scraper interval, mp start method."),
}

REGISTRY: tuple[Key, ...] = (
    Key(
        "database_url",
        str,
        "sqlite:///./affiliatebot.db",
        "llm",
        label="Database URL",
        kind="text",
        web=True,
        placeholder="postgresql+psycopg2://...",
    ),
    Key(
        "use_fake_clients",
        bool,
        False,
        "llm",
        label="Fake clients",
        kind="text",
        required=True,
        web=True,
        placeholder="false",
    ),
    Key(
        "groq_api_key", str, "", "llm", label="Groq API key", kind="secret", required=True, web=True
    ),
    Key(
        "groq_model",
        str,
        "llama-3.3-70b-versatile",
        "llm",
        label="Groq model",
        kind="text",
        web=True,
        placeholder="llama-3.3-70b-versatile",
    ),
    Key(
        "gemini_api_key",
        str,
        "",
        "llm",
        label="Gemini API key",
        kind="secret",
        required=True,
        web=True,
    ),
    Key(
        "gemini_model",
        str,
        "gemini-2.5-flash",
        "llm",
        label="Gemini model",
        kind="text",
        web=True,
        placeholder="gemini-2.5-flash",
    ),
    Key("groq_requests_per_minute", int, 30, "llm"),
    Key(
        "critic_llm_provider",
        str,
        "groq",
        "llm",
        note="groq = miễn phí + rate-limiter sẵn; gemini chỉ khi có key trả phí (free-tier 5 req/phút quá thấp).",
    ),
    Key("brain_enabled", bool, False, "llm"),
    Key("v5_brain_enabled", bool, True, "llm"),
    Key("input_gate_enabled", bool, True, "llm"),
    Key("llm_copywriter_model", str, "gemini-2.5-flash", "llm"),
    Key("llm_critic_model", str, "gemini-2.5-flash", "llm"),
    Key("llm_daily_budget_usd", float, 5.0, "llm"),
    Key("llm_estimated_cost_per_campaign_usd", float, 0.03, "llm"),
    Key("llm_max_campaigns_per_day", int, 50, "llm"),
    Key("llm_budget_ledger_path", str, "storage/llm/budget_ledger.json", "llm"),
    Key("critic_threshold", float, 8.0, "llm"),
    Key("critic_max_loops", int, 3, "llm"),
    Key(
        "dashboard_api_key",
        str,
        "",
        "dashboard",
        label="API key dashboard",
        kind="secret",
        required=True,
        web=True,
    ),
    Key(
        "dashboard_password_hash",
        str,
        "",
        "dashboard",
        label="Mật khẩu đăng nhập",
        kind="secret",
        web=True,
    ),
    Key(
        "dashboard_session_secret",
        str,
        "",
        "dashboard",
        label="Session secret (tự tạo)",
        kind="secret",
        web=True,
    ),
    Key("api_host", str, "127.0.0.1", "dashboard"),
    Key("api_port", int, 8000, "dashboard"),
    Key("dashboard_session_hours", int, 12, "dashboard"),
    Key("dashboard_session_days", int, 30, "dashboard"),
    Key("dashboard_lockout_max_attempts", int, 5, "dashboard"),
    Key("dashboard_lockout_minutes", int, 15, "dashboard"),
    Key("dashboard_cookie_secure", bool, False, "dashboard"),
    Key("dashboard_cors_origins", str, "capacitor://localhost,http://localhost", "dashboard"),
    Key(
        "telegram_bot_token",
        str,
        "",
        "telegram",
        label="Bot token",
        kind="secret",
        required=True,
        web=True,
    ),
    Key(
        "telegram_chat_id",
        str,
        "",
        "telegram",
        label="Chat ID",
        kind="text",
        required=True,
        web=True,
    ),
    Key(
        "affiliate_link_provider",
        str,
        "shopee_cdp",
        "shopee_session",
        label="Affiliate provider",
        kind="text",
        required=True,
        web=True,
        placeholder="shopee_cdp",
    ),
    Key(
        "shopee_cdp_url",
        str,
        "http://127.0.0.1:9222",
        "shopee_session",
        label="Chrome CDP URL",
        kind="text",
        required=True,
        web=True,
        placeholder="http://127.0.0.1:9222",
    ),
    Key(
        "shopee_internal_base",
        str,
        "https://affiliate.shopee.vn",
        "shopee_session",
        label="Shopee internal base",
        kind="url",
        required=True,
        web=True,
        placeholder="https://affiliate.shopee.vn",
    ),
    Key("affiliate_link_template", str, "", "shopee_session"),
    Key("shopee_cookie_lock_path", str, "storage/config/shopee_cookie_lock.json", "shopee_session"),
    Key("shopee_internal_timeout_seconds", float, 45.0, "shopee_session"),
    Key("shopee_link_min_interval_seconds", int, 90, "shopee_session"),
    Key("shopee_link_max_per_hour", int, 12, "shopee_session"),
    Key("shopee_link_max_per_day", int, 120, "shopee_session"),
    Key("shopee_link_retry_delay_seconds", int, 1800, "shopee_session"),
    Key(
        "meta_ads_library_token",
        str,
        "",
        "sources",
        label="Meta Ads Library token",
        kind="secret",
        web=True,
    ),
    Key(
        "meta_ads_library_base",
        str,
        "https://graph.facebook.com",
        "sources",
        label="Meta Ads Library base",
        kind="url",
        web=True,
        placeholder="https://graph.facebook.com",
    ),
    Key(
        "youtube_trends_token",
        str,
        "",
        "sources",
        label="YouTube trends token",
        kind="secret",
        web=True,
    ),
    Key(
        "youtube_trends_base",
        str,
        "https://www.googleapis.com",
        "sources",
        label="YouTube trends base",
        kind="url",
        web=True,
        placeholder="https://www.googleapis.com",
    ),
    Key("meta_ads_library_path", str, "/v24.0/ads_archive", "sources"),
    Key("youtube_trends_path", str, "/youtube/v3/search", "sources"),
    # Bậc 3 — tự-học-trend THỜI TRANG (seed tay + YouTube tự tìm; KHÔNG API TikTok/Shopee).
    Key(
        "trend_ingest_enabled", bool, False, "sources",
        label="Bật tự-học-trend",
        note="Bật vòng gom trend thời trang (seed tay + YouTube tự tìm) → Gemini chưng cất thành công thức PENDING. Mặc định TẮT.",
    ),
    Key(
        "trend_ingest_interval_hours", int, 12, "sources",
        note="Chu kỳ loop YouTube tự tìm trend (giờ). Trend sáng tạo đổi theo ngày/tuần → 12-24h là đủ.",
    ),
    Key(
        "trend_youtube_keywords", str,
        "phối đồ nữ,outfit nữ,lookbook thời trang,mix đồ Gen Z,thời trang nữ trend",
        "sources",
        label="Từ khoá YouTube thời trang",
        note="CSV từ khoá để YouTube tự tìm Shorts thời trang làm nguồn trend.",
    ),
    Key(
        "youtube_data_api_key", str, "", "sources",
        label="YouTube Data API key",
        kind="secret", web=True,
        note="Key Google (YouTube Data API v3 search.list) cho nguồn 2 'YouTube tự tìm'. Rỗng = chỉ dùng seed tay.",
    ),
    Key(
        "trend_tiktok_download_enabled", bool, False, "sources",
        label="Cho tải TikTok/Reels (yt-dlp)",
        note="⚠️ Tải video TikTok/Reels người khác để HỌC CẤU TRÚC (yt-dlp) — xám ToS/bản quyền, tự chịu rủi ro. TẮT = chỉ nhận link YouTube. Chỉ trích cấu trúc, render mới hoàn toàn.",
    ),
    Key(
        "trend_auto_approve", bool, False, "sources",
        note="Tự duyệt công thức trend (PENDING→ACTIVE) không cần founder bấm. Mặc định TẮT — duyệt tay 100% giai đoạn đầu.",
    ),
    Key(
        "dispatch_provider",
        str,
        "mock",
        "dispatch",
        label="Dispatch provider",
        kind="text",
        required=True,
        web=True,
        placeholder="youtube|tiktok|meta",
    ),
    Key(
        "youtube_access_token",
        str,
        "",
        "dispatch",
        label="YouTube access token",
        kind="secret",
        web=True,
    ),
    Key(
        "youtube_privacy_status",
        str,
        "private",
        "dispatch",
        label="YouTube privacy",
        kind="text",
        web=True,
        placeholder="private|unlisted|public",
    ),
    Key(
        "youtube_category_id",
        str,
        "22",
        "dispatch",
        label="YouTube category id",
        kind="text",
        web=True,
        placeholder="22",
    ),
    Key("meta_graph_token", str, "", "dispatch", label="Meta Graph token", kind="secret", web=True),
    Key("meta_page_id", str, "", "dispatch", label="Meta page id", kind="text", web=True),
    Key(
        "instagram_business_id",
        str,
        "",
        "dispatch",
        label="Instagram business id",
        kind="text",
        web=True,
    ),
    Key(
        "meta_graph_version",
        str,
        "v24.0",
        "dispatch",
        label="Meta Graph version",
        kind="text",
        web=True,
        placeholder="v24.0",
    ),
    Key(
        "dispatch_golden_hours",
        str,
        "11:00-13:00,19:00-22:00",
        "dispatch",
        note="Khung giờ vàng đăng bài; rỗng/hỏng → fail-open đăng ngay.",
    ),
    Key("dispatch_timezone", str, "Asia/Ho_Chi_Minh", "dispatch"),
    Key("dispatch_slot_spacing_minutes", int, 45, "dispatch"),
    Key("youtube_api_key", str, "", "dispatch"),
    Key("youtube_oauth_client_id", str, "", "dispatch", label="YouTube OAuth client id", kind="text", web=True),
    Key(
        "youtube_oauth_client_secret",
        str,
        "",
        "dispatch",
        label="YouTube OAuth client secret",
        kind="secret",
        web=True,
    ),
    Key("youtube_refresh_token", str, "", "dispatch", label="YouTube refresh token", kind="secret", web=True),
    Key("dispatch_stale_minutes", int, 30, "dispatch"),
    Key("publish_center_enabled", bool, False, "dispatch"),
    Key("publish_first_platform", str, "youtube", "dispatch"),
    Key("max_auto_posts_per_channel_per_day", int, 3, "dispatch"),
    Key("publish_min_spacing_minutes", int, 30, "dispatch"),
    Key("publish_require_approval", bool, True, "dispatch"),
    Key("publish_live_confirm_required", bool, True, "dispatch"),
    Key(
        "publish_stale_minutes",
        int,
        30,
        "dispatch",
        note="V5 Publish: job kẹt PUBLISHING quá số phút này (process chết giữa lúc đăng) → reclaim về NEEDS_REVIEW cho người kiểm. KHÔNG tự đăng lại (tránh đăng trùng vì bài có thể đã lên).",
    ),
    Key(
        "revenue_provider",
        str,
        "mock",
        "revenue",
        label="Revenue provider",
        kind="text",
        required=True,
        web=True,
        placeholder="shopee_affiliate",
    ),
    Key("revenue_sync_interval_seconds", int, 3600, "revenue"),
    Key("category_weight_min", float, 0.65, "revenue"),
    Key("category_weight_max", float, 1.35, "revenue"),
    Key("category_explore_rate", float, 0.15, "revenue"),
    Key("learning_variant_min_clicks", int, 50, "revenue"),
    Key("learning_variant_min_orders", int, 3, "revenue"),
    Key("learning_hook_min_clicks", int, 50, "revenue"),
    Key("learning_hook_min_orders", int, 3, "revenue"),
    Key("learning_min_winner_delta", float, 0.05, "revenue"),
    Key("learning_exploration_rate", float, 0.15, "revenue"),
    Key("learning_exploration_decay", float, 0.02, "revenue"),
    Key("learning_exploration_min_rate", float, 0.03, "revenue"),
    Key("learning_ucb_c", float, 0.25, "revenue"),
    Key("pexels_api_key", str, "", "assets", label="Pexels API key", kind="secret", web=True),
    Key("pixabay_api_key", str, "", "assets", label="Pixabay API key", kind="secret", web=True),
    Key(
        "android_keystore_file",
        str,
        "",
        "release",
        label="Keystore file",
        kind="text",
        web=True,
        env_only=True,
    ),
    Key(
        "android_keystore_password",
        str,
        "",
        "release",
        label="Keystore password",
        kind="secret",
        web=True,
        env_only=True,
    ),
    Key(
        "android_key_alias",
        str,
        "",
        "release",
        label="Key alias",
        kind="text",
        web=True,
        env_only=True,
        placeholder="affiliatebot",
    ),
    Key(
        "android_key_password",
        str,
        "",
        "release",
        label="Key password",
        kind="secret",
        web=True,
        env_only=True,
    ),
    Key("vbee_app_id", str, "", "media_ai", label="Vbee app id", kind="secret", web=True),
    Key("vbee_api_token", str, "", "media_ai", label="Vbee API token", kind="secret", web=True),
    Key(
        "vbee_voice_code",
        str,
        "",
        "media_ai",
        label="Vbee voice code",
        kind="text",
        web=True,
        placeholder="mã giọng Vbee (xem doc Vbee)",
    ),
    Key(
        "vbee_voice_code_male",
        str,
        "",
        "media_ai",
        label="Vbee kho giọng NAM",
        kind="text",
        web=True,
        placeholder="CSV nhiều mã giọng nam",
    ),
    Key(
        "vbee_voice_code_female",
        str,
        "",
        "media_ai",
        label="Vbee kho giọng NỮ",
        kind="text",
        web=True,
        placeholder="CSV nhiều mã giọng nữ",
    ),
    Key(
        "gemini_tts_model",
        str,
        "gemini-2.5-flash-preview-tts",
        "media_ai",
        note="V8.3-Q2: model Gemini TTS (nhánh TTS_PROVIDER=gemini_tts).",
    ),
    Key("gemini_tts_voice_female", str, "Autonoe", "media_ai"),
    Key("gemini_tts_voice_male", str, "Puck", "media_ai"),
    Key("tts_provider", str, "edge", "media_ai"),
    Key("tts_voice", str, "vi-VN-HoaiMyNeural", "media_ai"),
    Key("tts_voice_male", str, "vi-VN-NamMinhNeural", "media_ai", note="Giọng edge-tts NAM (last-resort khi gemini/vbee fail) — tts_voice là giọng nữ."),
    Key("tts_jitter_pct", float, 1.5, "media_ai"),
    Key(
        "voice_speed",
        float,
        1.25,
        "media_ai",
        note="Tốc độ đọc chung (edge rate + gemini atempo): 1.0=bình thường, 1.15-1.25 nhanh kiểu quảng cáo (nói nhiều nội dung hơn). vbee dùng VBEE_SPEED_RATE riêng.",
    ),
    Key(
        "vbee_speed_rate",
        float,
        1.0,
        "media_ai",
        note="Nhịp đọc vbee: 1.15-1.25 hay cho quảng cáo; >1.3 khó nghe.",
    ),
    Key("vbee_callback_url", str, "https://example.com/vbee-callback", "media_ai"),
    Key("tts_timeout_seconds", int, 60, "media_ai"),
    Key("tts_daily_budget_usd", float, 0.0, "media_ai"),
    Key("tts_estimated_cost_per_call_usd", float, 0.0, "media_ai"),
    Key("tts_budget_ledger_path", str, "storage/tts/budget_ledger.json", "media_ai"),
    Key(
        "suno_api_key",
        str,
        "",
        "media_ai",
        label="Suno API key",
        kind="secret",
        web=True,
        note="sunoapi.org — TẠO THƯ VIỆN nhạc nền 1 LẦN (scripts.gen_music_library), KHÔNG gọi mỗi video (trả phí ~$0.02/call).",
    ),
    Key("suno_base_url", str, "https://api.sunoapi.org", "media_ai"),
    Key("suno_model", str, "V4_5", "media_ai"),
    Key("weight_trend", float, 0.25, "scoring"),
    Key("weight_sales", float, 0.25, "scoring"),
    Key("weight_intent", float, 0.2, "scoring"),
    Key("weight_commission", float, 0.3, "scoring"),
    Key("profit_threshold", float, 0.85, "scoring"),
    Key("shopee_xtra_min_commission_pct", float, 10.0, "scoring"),
    Key("xtra_tier_a_threshold", float, 0.7, "scoring"),
    Key("xtra_tier_b_threshold", float, 0.45, "scoring"),
    Key("xtra_min_price_vnd", float, 20000.0, "scoring"),
    Key("xtra_score_weights_json", str, "", "scoring"),
    Key("dedup_window_days", int, 15, "scoring"),
    Key("scraper_commit_batch_size", int, 100, "scoring"),
    Key("normalization_lower_percentile", float, 5.0, "scoring"),
    Key("normalization_upper_percentile", float, 95.0, "scoring"),
    Key("scoring_bounds_ewma_alpha", float, 0.3, "scoring"),
    Key(
        "category_weights",
        str,
        '{"default":{"trend":0.25,"sales":0.25,"intent":0.20,"commission":0.30},"fashion":{"trend":0.35,"sales":0.20,"intent":0.20,"commission":0.25},"tech":{"trend":0.20,"sales":0.20,"intent":0.35,"commission":0.25},"home":{"trend":0.20,"sales":0.30,"intent":0.20,"commission":0.30},"beauty":{"trend":0.30,"sales":0.15,"intent":0.25,"commission":0.30},"health":{"trend":0.15,"sales":0.20,"intent":0.40,"commission":0.25},"finance":{"trend":0.10,"sales":0.15,"intent":0.45,"commission":0.30}}',
        "scoring",
    ),
    Key("product_enrichment_provider", str, "none", "scoring"),
    Key("product_enrichment_rate_limit_seconds", float, 2.5, "scoring"),
    Key("piapi_api_key", str, "", "video"),
    Key("piapi_base_url", str, "https://api.piapi.ai", "video"),
    Key("piapi_upload_url", str, "https://upload.theapi.app/api/ephemeral_resource", "video"),
    Key("image_provider", str, "local", "video"),
    Key("video_provider", str, "seedance_piapi", "video"),
    Key("video_resolution", str, "480p", "video"),
    Key("video_premium_resolution", str, "720p", "video"),
    Key(
        "video_audio_mode",
        str,
        "auto",
        "video",
        note="auto = vbee đè giọng + audio Seedance hạ nền (mix); native = giữ nguyên audio Seedance (tiếng Việt hiện lơ lớ).",
    ),
    Key("video_use_native_audio", bool, True, "video"),
    Key("analyzer_llm_enabled", bool, True, "video"),
    Key("analyzer_llm_timeout_seconds", int, 25, "video"),
    Key(
        "autopilot_enabled",
        bool,
        False,
        "video",
        hot=True,
        note="Gate .env AND toggle runtime automation.json — cả hai bật mới chạy.",
    ),
    Key("autopilot_max_per_day", int, 3, "video"),
    Key("autopilot_min_tier", str, "A", "video"),
    Key("autopilot_allow_tier_b", bool, False, "video"),
    Key("autopilot_min_promo_appeal", int, 6, "video"),
    Key("autopilot_sources", str, "shopee_xtra,manual_ingest", "video"),
    Key(
        "autopilot_retry_limit",
        int,
        2,
        "video",
        note="Autopilot: số lần TỐI ĐA tạo job cho 1 SP khi job trước FAILED kỹ thuật (provider/timeout — lỗi TẠM). QA_FAIL/REJECTED (lỗi thật) KHÔNG retry. =1 là tắt retry (hành vi cũ).",
    ),
    Key("video_draft_resolution", str, "480p", "video"),
    Key("video_draft_seconds", int, 5, "video"),
    Key("video_final_seconds", int, 15, "video"),
    Key("video_daily_budget_usd", float, 5.0, "video"),
    Key("video_max_per_day", int, 10, "video"),
    Key("video_engine_output_dir", str, "storage/video_engine", "video"),
    Key("video_gemini_image_model", str, "gemini-2.5-flash-image", "video"),
    Key("video_image_cost_usd", float, 0.039, "video"),
    Key("fx_vnd_per_usd", float, 25400.0, "video",
        note="Tỷ giá USD→VND để HIỂN THỊ ước tính chi phí (xấp xỉ, không phải giao dịch). FE analytics.js có hằng FX_VND_PER_USD mirror — đổi thì đổi cả 2."),
    Key(
        "video_clean_plate_enabled",
        bool,
        True,
        "video",
        note="Tách SP khỏi ảnh marketing GIỮ PIXEL GỐC (crop+seg, không vẽ lại bằng AI) làm khung đầu i2v; tắt = ảnh gốc.",
    ),
    Key(
        "video_product_hero_seconds",
        int,
        0,
        "video",
        note="Beat khoe SP đầu video = ảnh sạch + Ken Burns pan/zoom (KHÔNG i2v → giữ 100% pixel SP); 0 = tắt, gợi ý 2-3s. Chỉ chế độ voiceover.",
    ),
    Key(
        "video_seedance_prices_json",
        str,
        '{"seedance-2-fast":{"480p":0.08,"720p":0.16},"seedance-2":{"480p":0.10,"720p":0.20,"1080p":0.50},"seedance-2-fast-less-restriction":{"480p":0.10,"720p":0.20},"seedance-2-less-restriction":{"480p":0.125,"720p":0.25,"1080p":0.625}}',
        "video",
    ),
    Key("video_piapi_timeout_seconds", float, 60.0, "video"),
    Key("video_piapi_poll_interval_seconds", float, 5.0, "video"),
    Key("video_piapi_max_wait_seconds", int, 900, "video"),
    Key("video_worker_poll_seconds", float, 3.0, "video"),
    Key(
        "video_cta_tail_seconds",
        int,
        0,
        "video",
        note="Đuôi CTA local (GHÉP ẢNH SP + giá + MUA NGAY) xfade sau clip chính. Mặc định 0 = TẮT (clip không ghép ảnh, theo yêu cầu). >0 (gợi ý 6) để bật lại — chỉ chế độ voiceover.",
    ),
    Key(
        "video_tail_transition",
        str,
        "fade",
        "video",
        note="Hiệu ứng nối clip chính → đuôi CTA: fade | fadeblack | smoothleft…(xfade transitions).",
    ),
    Key(
        "director_critic_threshold",
        float,
        7.0,
        "video",
        note="V8.3-Q4: critic chấm <ngưỡng → Director viết lại 1 lần; bản 2 <5 → job tay cảnh báo, autopilot skip.",
    ),
    Key(
        "strategist_enabled",
        bool,
        True,
        "video",
        note="V8.5: bật Affiliate Strategist — phân tích SP + chọn góc thuyết phục + beat-plan bám format (lấy CẤU TRÚC từ template đã chọn, không copy SP trong template) TRƯỚC Director. false → Director chạy như cũ.",
    ),
    Key(
        "channel_theme_doc",
        str,
        "TAI-LIEU-GOC-KENH-CHIN-CHUN.md",
        "video",
        label="File chủ đề kênh",
        note="Đường dẫn file chủ đề kênh (markdown) nạp vào prompt Director để video bám tông/ngách/luật khử-AI của kênh; tương đối tính từ project root; rỗng = tắt.",
    ),
    Key(
        "director_review_max_rounds",
        int,
        3,
        "video",
        note="Số vòng review→viết-lại tối đa của Director (TỰ NÂNG CẤP kịch bản). 3 = viết + tối đa 2 lần Critic-chấm→viết-lại theo rewrite_hints, GIỮ BẢN ĐIỂM CAO NHẤT, dừng sớm khi đạt ngưỡng (director_critic_threshold). 1 = tắt vòng sửa (viết 1 lần). Mỗi vòng thêm tốn ~2 call LLM rẻ (director+critic), KHÔNG tốn render. Founder yêu cầu prompt output luôn chất lượng cao nhất → mặc định 3.",
    ),
    Key(
        "director_review_min_product_fit",
        float,
        6.0,
        "video",
        note="V8.5: ngưỡng tối thiểu chiều product_fit (kịch bản KHỚP đúng SP, không rò SP khác). Dưới ngưỡng → buộc viết lại dù điểm tổng đạt.",
    ),
    Key(
        "longform_critic_enabled",
        bool,
        True,
        "video",
        note="long_narrative: bật content+structural critic (đa vòng auto-improve) TRƯỚC render. false = chỉ generate_script 1 lần.",
    ),
    Key(
        "longform_critic_max_rounds",
        int,
        3,
        "video",
        note="long_narrative: số vòng tối đa critic→viết-lại (1 = tắt loop; 3 = viết + tối đa 2 lần sửa theo rewrite_hints, giữ bản điểm cao nhất). Mỗi vòng vài LLM text call (Groq ~free), KHÔNG tốn render.",
    ),
    Key(
        "longform_critic_min_score",
        float,
        7.0,
        "video",
        note="long_narrative: ngưỡng tổng điểm content critic (0-10). Dưới ngưỡng → viết lại kịch bản.",
    ),
    Key(
        "longform_critic_min_cakhia",
        float,
        1.0,
        "video",
        note="long_narrative: SÀN RIÊNG cho chiều 'cakhia' (hài/cà khịa) VÀ 'hook' (0-2). Mặc định 1.0 = phải CÓ chút hài + hook, chống lọt kịch bản 'đọc tin trơn' điểm-tổng-cao-nhưng-nhạt. 0 = tắt sàn. Chỉ áp khi LLM critic chấm được (LLM lỗi/fail-open → bỏ qua sàn này).",
    ),
    Key(
        "longform_fact_critic_enabled",
        bool,
        True,
        "video",
        note="long_narrative: đối chiếu narration vs nguồn tin (chống bịa số/tên). Cần source_text; rỗng thì bỏ qua.",
    ),
    Key(
        "longform_fact_critic_strict",
        bool,
        False,
        "video",
        note="long_narrative: True = phát hiện bịa RÕ thì FAIL job; False = chỉ cảnh báo (READY + cờ fact_warn).",
    ),
    Key(
        "longform_min_beats",
        int,
        5,
        "video",
        note="long_narrative: số beat tối thiểu cho structural gate (dưới mức → cờ cấu trúc).",
    ),
    Key(
        "longform_broll_enabled",
        bool,
        False,
        "video",
        note="long_narrative: tải footage Pexels xen vào hình. MẶC ĐỊNH TẮT — kênh là tranh vẽ AI, footage stock theo keyword hay LẠC ĐỀ + lệch phong cách. Bật lại nếu muốn chèn footage thật.",
    ),
    Key(
        "longform_youtube_publish_enabled",
        bool,
        False,
        "video",
        note="long_narrative: cổng AN TOÀN cho đăng YouTube THẬT (/youtube-video/{id}/publish). MẶC ĐỊNH TẮT theo RULES (không đăng thật khi test). Bật ở Credential Center khi đã xem kỹ + muốn đăng thật. Tắt = chặn mọi lần đăng (kể cả unlisted/public).",
    ),
    Key(
        "longform_tts_engine",
        str,
        "gemini",
        "video",
        note="long_narrative: engine giọng đọc — 'gemini' (MẶC ĐỊNH: Gemini 2.5 TTS, nhấn nhá per-block theo field context: climax→hét, whisper→thì thầm; AUTO lùi Vbee khi HẾT CREDIT — cả video còn lại dùng Vbee để giữ giọng đồng nhất, KHÔNG trộn) | 'vbee' (rẻ, ổn định, nhưng đọc phẳng không cảm xúc) | 'edge' (edge-tts Microsoft, MIỄN PHÍ hẳn, không cần key — dùng khi TEST để tiết kiệm credit; giọng máy hơn Gemini) | 'vieneu' (giọng CLONE local — VieNeu, MIỄN PHÍ + chạy ngay máy này + CÓ cảm xúc native; cần cài daemon ở voiceclone_daemon_dir). Gemini/Vbee cần cấu hình key.",
    ),
    Key(
        "voiceclone_ref_audio_path",
        str,
        "",
        "video",
        note="long_narrative/film_recap (engine 'vieneu'): đường dẫn file WAV mẫu giọng để CLONE. RỖNG = dùng nvl_ref.wav mặc định trong voiceclone_daemon_dir. ~8s sạch đủ clone; muốn chuẩn hơn thu 10-30 phút.",
    ),
    Key(
        "voiceclone_emotion",
        str,
        "natural",
        "video",
        note="long_narrative/film_recap (engine 'vieneu'): cảm xúc giọng clone VieNeu. Mặc định 'natural' (đã có nhấn nhá nhẹ).",
    ),
    Key(
        "voiceclone_speed",
        float,
        1.08,
        "video",
        note="long_narrative/film_recap (engine 'vieneu'): tốc độ đọc (atempo, GIỮ cao độ). 1.0 = gốc; 1.08 = nhanh hơn xíu KHÔNG hụt hơi. Tránh >1.12 kẻo lệch chữ.",
    ),
    Key(
        "voiceclone_silence_p",
        float,
        0.12,
        "video",
        note="long_narrative/film_recap (engine 'vieneu'): độ dài khoảng nghỉ giữa câu (giây). Nhỏ = nhịp gọn; lớn = thư thả.",
    ),
    Key(
        "voiceclone_daemon_dir",
        str,
        r"C:\Users\NTD\vieneu_tts",
        "video",
        note="long_narrative/film_recap (engine 'vieneu'): thư mục cài daemon VieNeu (venv RIÊNG + vieneu_daemon.py + nvl_ref.wav). Engine 'vieneu' spawn daemon từ đây.",
    ),
    Key(
        "voiceclone_daemon_port",
        int,
        8771,
        "video",
        note="long_narrative/film_recap (engine 'vieneu'): cổng HTTP local của daemon VieNeu.",
    ),
    Key(
        "longform_character_ref",
        str,
        "",
        "video",
        note="long_narrative: đường dẫn ảnh NHÂN VẬT DẪN cố định (1-2 ảnh, ngăn bởi phẩy) truyền làm reference khi gen ảnh doodle → Gemini giữ nhân vật nhất quán mọi beat. Rỗng = tắt (hành vi cũ). Bật cho kênh có nhân vật (vd storage/characters/presenter.png).",
    ),
    Key(
        "longform_character_dir",
        str,
        "storage/characters",
        "video",
        note="long_narrative visual_mode=doodle_cutout: thư mục chứa thư viện pose nhân vật (library/*.png gen-sẵn-1-lần) + expression_manifest.json. character_library.py đọc từ đây để dán nhân vật cut-out vào cảnh.",
    ),
    Key(
        "film_recap_daily_budget_usd",
        float,
        2.0,
        "video",
        note="film_recap (review phim): ngân sách USD/ngày RIÊNG (sổ provider='film_recap', tách khỏi video_engine) để test recap không ngốn budget luồng affiliate.",
    ),
    Key(
        "film_recap_clip_max_seconds",
        int,
        90,
        "video",
        note="film_recap: độ dài tối đa (giây) của clip review xuất ra.",
    ),
    Key(
        "film_recap_source_max_filesize_mb",
        int,
        200,
        "video",
        note="film_recap: trần dung lượng (MB) clip nguồn tải qua yt-dlp (chống tải nhầm video quá dài).",
    ),
    Key(
        "film_recap_recap_beats",
        int,
        7,
        "video",
        note="film_recap recap: số câu bình luận (beat) ~ số clip minh hoạ cắt từ nguồn.",
    ),
    Key(
        "film_recap_scene_min_seconds",
        float,
        1.2,
        "video",
        note="film_recap recap B2: bỏ cảnh ngắn hơn (giây) khi chấm cảnh — né chớp/transition.",
    ),
    Key(
        "film_recap_scene_max_seconds",
        float,
        8.0,
        "video",
        note="film_recap recap B2: trần độ dài 1 clip minh hoạ (giây) — né cảnh tĩnh lê thê.",
    ),
    Key(
        "longform_visual_engine",
        str,
        "doodle_cutout",
        "video",
        note="long_narrative: chế độ DỰNG HÌNH mặc định khi không truyền visual_mode. 'vuive_layered' = đạo diễn AI đa-lớp (Stage 2: shot_planner→critic→compositor, hình động kiểu Vui Vẻ); 'doodle_cutout' = cảnh tĩnh ghép sẵn (FALLBACK an toàn, look hiện tại); 'doodle'/'photo_meme'/'hybrid' giữ nguyên. vuive_layered hỏng tự rơi về doodle_cutout.",
    ),
    Key(
        "longform_image_provider",
        str,
        "local",
        "video",
        note="long_narrative: nguồn SINH ảnh doodle. Flow chính chỉ dùng 'local' (SDXL+LoRA); 'gemini'/'hybrid' bị chặn để không fallback sinh ảnh bằng Gemini.",
    ),
    # SDXL local image-gen (long_narrative Pha B): đọc bởi GPU subprocess image_stage/local_worker.py
    # qua os.getenv (venv riêng), parent image_stage/local.py truyền qua env → env_only (không phải Settings field).
    Key("longform_sdxl_model", str, "stabilityai/stable-diffusion-xl-base-1.0", "video", env_only=True,
        note="SDXL base model (HF repo/path)."),
    Key("longform_sdxl_lora", str, "", "video", env_only=True,
        note="LoRA phong cách doodle (repo/path); rỗng = chỉ base + prompt phẳng."),
    Key("longform_sdxl_lora_w", float, 0.8, "video", env_only=True, note="Alpha (độ mạnh) LoRA."),
    Key("longform_sdxl_trigger", str, "", "video", env_only=True, note="Trigger word của LoRA."),
    Key("longform_sdxl_steps", int, 20, "video", env_only=True, note="Số bước khử nhiễu SDXL."),
    Key("longform_sdxl_size", int, 768, "video", env_only=True,
        note="Cạnh ảnh px (768 nhanh hơn ~2× + đỡ VRAM trên 3060 so với 1024)."),
    Key("longform_sdxl_ref_strength", float, 0.58, "video", env_only=True,
        note="Độ bám ảnh tham chiếu (0.15–0.9)."),
    Key("longform_sdxl_ref_mode", str, "trace", "video", env_only=True, note="Chế độ dùng ảnh ref (trace…)."),
    Key("longform_sdxl_ref_remove_bg", str, "1", "video", env_only=True,
        note="1=tách nền ảnh ref; 0/false/no=giữ nền."),
    Key(
        "longform_trends_geo",
        str,
        "VN",
        "video",
        note="long_narrative: geo cho Google Trends Daily RSS (thể loại 'đang hot') — vd 'VN', 'US'. Rỗng = TẮT lấy chủ đề trend (chỉ còn RSS thể loại). Free, no-key.",
    ),
    Key(
        "auto_approve_require_qa_v2",
        bool,
        True,
        "video",
        note="V8.3-Q5: autopilot CHỈ tự duyệt khi text_scan_ok + audio_ok (false = hành vi cũ chỉ cần QA pass).",
    ),
    Key(
        "qa_logo_legible_exception_score",
        float,
        0.90,
        "video",
        note="QA (fix job 36): clip khớp SP với score >= ngưỡng này KHÔNG bị loại chỉ vì logo/nhãn không "
             "đọc được (vd nhãn TRONG cổ áo bị che khi mặc). score thấp + logo mờ VẪN bị chặn (chống SP sai).",
    ),
    Key(
        "video_overlay_hidden_kinds",
        str,
        "hook,price,cta",
        "video",
        note="CSV các 'kind' overlay KHÔNG vẽ lên clip (vẫn giữ trong giọng đọc). Mặc định ẩn HẾT "
             "(hook,price,cta) = clip KHÔNG chữ, theo yêu cầu. Để TRỐNG nếu muốn hiện hết chữ.",
    ),
    Key(
        "piapi_image_max_size_mb",
        int,
        2,
        "video",
        note="seedance:76 — trần dung lượng ảnh khi PiAPI chặn upload → nhúng base64 data-URI vào create_task. "
             "Ảnh > ngưỡng → báo lỗi rõ (tránh payload phình + timeout). Ảnh URL công khai (https) KHÔNG bị ảnh hưởng.",
    ),
    Key("bg_music_volume", float, 0.07, "render"),
    Key(
        "bg_music_enabled",
        bool,
        True,
        "render",
        note="Bật nhạc nền cho clip. Voiceover mode: nhạc chạy dưới giọng. Clip THÔ/không lời: nhạc bản-quyền-sạch là tiếng chính (tự chọn theo ngành). Cần file mp3/wav trong BG_MUSIC_DIR (có sẵn 6 track). Mặc định BẬT.",
    ),
    Key("bg_music_dir", str, "storage/video_engine/library/music", "render"),
    Key("render_workers", int, 4, "render"),
    Key("render_gpu_safe_workers", int, 1, "render"),
    Key("ffmpeg_video_codec", str, "libx264", "render"),
    Key("render_formats", str, "9:16", "render"),
    Key("compose_polish_mode", str, "light", "render"),
    Key("render_require_asset_license", bool, False, "render"),
    Key("render_require_qa_pass", bool, True, "render"),
    Key("render_vram_guard_enabled", bool, True, "render"),
    Key("render_vram_guard_max_used_pct", float, 85.0, "render"),
    Key("render_vram_guard_min_free_mb", int, 1024, "render"),
    Key("render_vram_guard_incident_cooldown_minutes", int, 15, "render"),
    Key("render_stale_minutes", int, 30, "render"),
    Key("auto_approve_script", bool, False, "automation", hot=True),
    Key("auto_approve_video", bool, False, "automation", hot=True),
    Key("auto_dispatch", bool, False, "automation", hot=True),
    Key(
        "auto_sensitive_categories",
        str,
        "beauty,health,finance,medical,weight_loss",
        "automation",
        hot=True,
    ),
    Key("auto_dispatch_privacy", str, "private", "automation", hot=True),
    Key("auto_dispatch_max_per_hour", int, 6, "automation", hot=True),
    Key("browser_qa_harness_enabled", bool, False, "browser_qa"),
    Key("browser_qa_headless", bool, False, "browser_qa"),
    Key("browser_qa_max_concurrent", int, 2, "browser_qa"),
    Key("browser_qa_default_timeout_seconds", int, 30, "browser_qa"),
    Key("browser_qa_storage_dir", str, "storage/browser-qa", "browser_qa"),
    Key("browser_qa_asset_blocking", str, "media_only", "browser_qa"),
    Key("browser_qa_cdp_port", int, 9222, "browser_qa"),
    Key("browser_qa_min_start_jitter_seconds", int, 30, "browser_qa"),
    Key("browser_qa_max_start_jitter_seconds", int, 900, "browser_qa"),
    Key("browser_qa_max_cpu_pct", float, 85.0, "browser_qa"),
    Key("browser_qa_max_ram_pct", float, 85.0, "browser_qa"),
    Key("browser_qa_max_disk_pct", float, 95.0, "browser_qa"),
    Key("browser_qa_max_gpu_util_pct", float, 95.0, "browser_qa"),
    Key("browser_qa_profile_failure_cooldown_seconds", int, 900, "browser_qa"),
    Key("browser_qa_running_stale_seconds", int, 1800, "browser_qa"),
    Key("lead_inbox_enabled", bool, False, "leads"),
    Key("comment_sync_mode", str, "disabled", "leads"),
    Key("dm_automation_mode", str, "disabled", "leads"),
    Key("lead_reply_require_approval", bool, True, "leads"),
    Key("lead_intent_llm_enabled", bool, False, "leads"),
    Key("public_base_url", str, "", "ops"),
    Key("storage_dir", str, "./storage", "ops"),
    Key("storage_min_free_mb", int, 512, "ops"),
    Key("live_smoke_report_path", str, "logs/go_live_live.json", "ops"),
    Key("live_smoke_audit_report_path", str, "logs/live_smoke_audit.json", "ops"),
    Key("live_smoke_max_age_hours", int, 24, "ops"),
    Key("backup_retention_days", int, 14, "ops"),
    Key("log_dir", str, "logs", "ops"),
    Key("log_level", str, "INFO", "ops"),
    Key("log_retention_days", int, 10, "ops"),
    Key("audio_workdir_retention_days", int, 3, "ops"),
    Key(
        "mp_start_method",
        str,
        "",
        "ops",
        note='"" = auto theo HĐH (Linux=fork, Windows=spawn). KHÔNG đặt "fork" trên Windows — crash boot.',
    ),
    Key("event_queue_maxsize", int, 1000, "ops"),
    Key("scraper_interval_seconds", int, 300, "ops"),
    Key(
        "scraper_import_secret",
        str,
        "",
        "ops",
        note='Khớp header X-Harvest-Secret của extension "Máy gặt"; rỗng → endpoint 401.',
    ),
    Key("scraper_import_max", int, 0, "ops"),
    Key("supervisor_check_interval_seconds", int, 15, "ops"),
    Key("supervisor_restart_limit", int, 5, "ops"),
    Key("supervisor_stable_seconds", int, 600, "ops"),
    Key("supervisor_disabled_realert_seconds", int, 21600, "ops"),
    Key("reconcile_interval_seconds", int, 300, "ops"),
    Key("brain_retry_limit", int, 3, "ops"),
    # ── Màn "Tạo video từ link sản phẩm TikTok" (kênh Chin & Chun) ──────────
    Key(
        "tiktok_ingest_enabled",
        bool,
        True,
        "sources",
        label="Bật ingest link TikTok",
        kind="text",
        web=True,
        note="Bật màn 'Tạo video từ link sản phẩm TikTok' + endpoint /api/v8/tiktok/*.",
    ),
    Key(
        "tiktok_ingest_browser",
        str,
        "cdp",
        "sources",
        note="Lớp 2 lấy đủ gallery: cdp = Chrome đăng nhập (reuse SHOPEE_CDP_URL) | extension | manual. "
        "Lớp 1 (og: 1 ảnh) luôn chạy ngầm bằng HTTP, không cần browser.",
    ),
    Key(
        "tiktok_video_sample_enabled",
        bool,
        True,
        "sources",
        label="Bật phân tích video mẫu → prompt",
        kind="text",
        web=True,
        note="Bật ô 'Upload video mẫu → tạo prompt Seedance tái tạo' ở màn Tạo video TikTok "
        "(endpoint /api/v8/tiktok/analyze-video). Cần GEMINI_API_KEY để đọc video.",
    ),
    Key(
        "user_music_volume",
        float,
        0.85,
        "render",
        note="Âm lượng nhạc người dùng dán (clip không lời = nhạc làm tiếng chính; cao hơn BG_MUSIC_VOLUME nền).",
    ),
    Key(
        "tiktok_audio_download_enabled",
        bool,
        False,
        "media_ai",
        note="Tải ĐÚNG nhạc trend từ clip TikTok (yt-dlp) — rủi ro bản quyền cho video CÓ link affiliate. "
        "Mặc định TẮT; bật thủ công + tự chịu rủi ro. Tắt → dùng nhạc bản-quyền-sạch (BG_MUSIC_DIR).",
    ),
    Key("tiktok_audio_trim_seconds", int, 20, "media_ai", note="Độ dài cắt nhạc cố định cho màn link TikTok."),
    Key("tiktok_audio_dir", str, "storage/audio/tiktok", "media_ai"),
)
